import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
p.on('pageerror', e => console.log('[pageerror]', e.message.slice(0, 300)));
p.on('console', m => { const t = m.text(); if (t.includes('failed') && !t.includes('GL Driver')) console.log('[c]', t.slice(0, 200)); });
await p.goto('http://localhost:8741/index.html');
await p.waitForFunction('window.__model !== undefined', { timeout: 120000 });
const stats = await p.evaluate(() => document.getElementById('hud-stats').innerText);
console.log('[stats]', stats);
await b.close();
